### ISSUE TITLE
io.github.thibaultbee.streampack.error.StreamPackError: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by hemant-cloudfeather** [ThibaultBee/StreamPack#42]
Hi,
I am trying to run the screen recorder demo app in my Oneplus 9RT device (android 12). I have selected the RTMP protocol and also set the server url in settings.  Following is the settings which I have used:-
![App_settings](https://user-images.githubusercontent.com/96680318/181918361-fcb51c93-1c96-4555-a9d7-cc60832101c0.jpg)

But when pressing the record screen button, I am getting the following crash in my phone:-
```
An error occurred                                                                                                                                                           
io.github.thibaultbee.streampack.error.StreamPackError: java.lang.IllegalArgumentException                                                                                  
	at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.configure(BaseStreamer.kt:242)                                                                         
	at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.configure(BaseStreamer.kt:264)                                                                         
	at io.github.thibaultbee.streampack.screenrecorder.ScreenRecorderService.onStartCommand(ScreenRecorderService.kt:314)                                                   
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4807)                                                                                               
	at android.app.ActivityThread.access$2100(ActivityThread.java:254)                                                                                                      
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2222)                                                                                                 
	at android.os.Handler.dispatchMessage(Handler.java:106)                                                                                                                 
	at android.os.Looper.loopOnce(Looper.java:233)                                                                                                                          
	at android.os.Looper.loop(Looper.java:344)                                                                                                                              
	at android.app.ActivityThread.main(ActivityThread.java:8212)                                                                                                            
	at java.lang.reflect.Method.invoke(Native Method)                                                                                                                       
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)                                                                                    
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)                                                                                                        
Caused by: java.lang.IllegalArgumentException                                                                                                                               
	at android.media.MediaCodec.native_configure(Native Method)                                                                                                             
	at android.media.MediaCodec.configure(MediaCodec.java:2176)                                                                                                             
	at android.media.MediaCodec.configure(MediaCodec.java:2092)                                                                                                             
	at io.github.thibaultbee.streampack.internal.encoders.MediaCodecEncoder.configureCodec(MediaCodecEncoder.kt:180)                                                        
	at io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder.createVideoCodec(VideoMediaCodecEncoder.kt:102)                                            
	at io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder.configure(VideoMediaCodecEncoder.kt:59)                                                    
	at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.configure(BaseStreamer.kt:237)                                                                         
	at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.configure(BaseStreamer.kt:264)                                                                         
	at io.github.thibaultbee.streampack.screenrecorder.ScreenRecorderService.onStartCommand(ScreenRecorderService.kt:314)                                                   
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4807)                                                                                               
	at android.app.ActivityThread.access$2100(ActivityThread.java:254)                                                                                                      
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2222)                                                                                                 
	at android.os.Handler.dispatchMessage(Handler.java:106)                                                                                                                 
	at android.os.Looper.loopOnce(Looper.java:233)                                                                                                                          
	at android.os.Looper.loop(Looper.java:344)                                                                                                                              
	at android.app.ActivityThread.main(ActivityThread.java:8212) 
        at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)                                                                                    
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by ThibaultBee** [comment]
Hi,
It seems that your video encoder does not accept the configuration but I can't say why. Do you have any other logs before or after this?

**Comment by hemant-cloudfeather** [comment]
Hi,
These were the only error logs, rest were normal I guess. 
And the above code snippet returns 120 as fps in my device.

**Comment by ThibaultBee** [comment]
Hi,
Could you check that your encoder supports 120 fps? The screen recorder streamer has a field: `streamer.helper.video.getSupportedFramerate(MediaFormat.MIMETYPE_VIDEO_AVC)`

Alternatively you can set the `fps` of the `VideoConfig` in the `ScreenRecorderService` (method `createVideoConfigFromBundle`) to 30 and test your live again.

**Comment by ThibaultBee** [comment]
On my phone `getSupportedFramerate` returns `[0, 240]`. I am pretty sure that the framerate of your screen is supported as well.

So I read the code source. The issue could be with the encoder profile/level settings. On most device, when profile and/or level are not supported, the MediaCodec API returns a `MediaCodec.CodecException` which may be not the case on your phone. The `MediaCodec.CodecException` is catched and I try to start the encoder without the profile/level settings but if the MediaCodec API throw a IllegalArgumentException, it just returns the exception.

Could you remove these 2 lines in ScreenRecorderService?
```
            level = bundle.getInt(LEVEL),
            profile = bundle.getInt(PROFILE)
```

**Comment by ThibaultBee** [comment]
By the way, in the next version of StreamPack, the library will provide Screen recorder Service. Check out for the develop branch.

**Comment by hemant-cloudfeather** [comment]
Hi ThibaultBee,
Sorry for late reply but after commenting the level and profile lines from ScreenRecorderService, the screen record streaming worked fine. 
Thank you for your response. Will also try out the new version once it is available.

**Comment by ThibaultBee** [comment]
The new library version will come with service that you could be customizable. It will simplify integration in an application. If you already have your custom Service the new version won't bring anything new.
