### ISSUE TITLE
Support for vp8/vp9 encoders for video

### ISSUE THREAD

**Issue by rranjan14** [ThibaultBee/StreamPack#60]
Many android devices do not have H264/H265 encoders. But they do have either vp8 or vp9 encoder. How about extending support to these encoders as well?

**Comment by ThibaultBee** [comment]
Hi,
All Android devices have H.264 encoders as specified here: https://developer.android.com/guide/topics/media/media-formats#video-formats
As you can see VP8 and VP9 encoders are not mandatory.
By the way, if you are looking to use VP8 or VP9 over RTMP, there aren't any official specification. Not sure about MPEG-TS (SRT container).

Anyway, I can add support for these encoders but as H.264 encoder are mandatory, I don't see the point.

**Comment by rranjan14** [comment]
Take this for e.g., [Redmi K50i 5g](https://www.devicespecifications.com/en/model/ddd55a13). When you'll check available codecs, you won't find H.264. Also, many low end android devices don't have them.

It'll really be great if you add support for vp8 and vp9 as well.

**Comment by ThibaultBee** [comment]
Have you try to found H.264 in these devices? Do you have the Redmi K50i and the Xiami Mi 11 Ultra? In that case, could you dump the video encoders list (screenshot, API, or xml)?

As I said, h.264 encoder are in every Android device, that's the Android specifications.

**Comment by rranjan14** [comment]
Unfortunately, I do not own these devices. But I can attach a few screenshots taken from [DeviceSpecifications](https://www.devicespecifications.com/en)

Redmi K50i 5g:
<img width="1150" alt="ScreenShot 2022-12-26 at 13 50 55" src="https://user-images.githubusercontent.com/47914095/209526499-32952da3-4012-4684-bb73-5f2035d8c4bd.png">

Xiaomi Mi 11 Ultra:
<img width="1134" alt="ScreenShot 2022-12-26 at 13 51 48" src="https://user-images.githubusercontent.com/47914095/209526567-f5a0edb5-3b28-4870-a05b-74eb4400efa6.png">

Pixel 6(this has H.264, attaching just to point out the difference):
<img width="1087" alt="ScreenShot 2022-12-26 at 14 12 18" src="https://user-images.githubusercontent.com/47914095/209526692-24ada685-12fc-4ba4-8227-cd4ac10838c4.png">

Also, attaching crash logs for Redmi K50i 5g:
```
Caused by java.security.InvalidParameterException: Failed to create codec for: {mime=video/avc, width=720, height=1280}
       at io.github.thibaultbee.streampack.internal.encoders.MediaCodecEncoder.createCodec(MediaCodecEncoder.kt:185)
       at io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder.createVideoCodec(VideoMediaCodecEncoder.kt:81)
       at io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder.configure(VideoMediaCodecEncoder.kt:59)
       at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.resetVideo(BaseStreamer.kt:364)
       at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.stopStream(BaseStreamer.kt:321)
       at io.github.thibaultbee.streampack.streamers.bases.BaseCameraStreamer.stopPreview(BaseCameraStreamer.kt:126)
       at io.github.thibaultbee.streampack.streamers.bases.BaseCameraStreamer.release(BaseCameraStreamer.kt:134)
       at io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.configure(BaseStreamer.kt:243)
       at video.api.livestream.ApiVideoLiveStream.setVideoConfig(ApiVideoLiveStream.kt:86)
       at video.api.reactnative.livestream.ReactNativeLiveStreamView.setVideoConfig(ReactNativeLiveStreamView.kt:59)
       at video.api.reactnative.livestream.ReactNativeLiveStreamViewManager.setVideoConfig(ReactNativeLiveStreamViewManager.kt:62)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:86)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1166)
       at android.view.Choreographer.doCallbacks(Choreographer.java:920)
       at android.view.Choreographer.doFrame(Choreographer.java:830)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1150)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8290)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by ThibaultBee** [comment]
As there isn't any video encoder in the list, I guess that DeviceSpecifications is not reliatable in term of video encoders.
For your crash, we already discuss it there: https://github.com/apivideo/api.video-reactnative-live-stream/issues/50.

This issue https://github.com/apivideo/api.video-reactnative-live-stream/issues/39 has already been fixed in StreamPack. You will have to wait for its integration in the api.video RN live stream.
