### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by HitanshuIntern** [ThibaultBee/StreamPack#69]
### Version

75df86adc4733942fbd35468a6c19444e4b91354

### Environment that reproduces the issue

Pixel 6 Pro Android 12

### RTMP/SRT/... Server

SRT

### Is it reproducible in the demos application?

Yes

### Reproduction steps

using a local SRT Stream server on Linux System and Try to run the app in emulator 

### Expected result

It should stream the video

### Actual result

E/StandaloneCoroutine: startStream failed
    java.net.ConnectException: Connection setup failure: connection timed out
        at io.github.thibaultbee.srtdroid.models.Socket.connect(Socket.kt:241)
        at io.github.thibaultbee.srtdroid.models.Socket.connect(Socket.kt:254)
        at io.github.thibaultbee.streampack.ext.srt.internal.endpoints.SrtProducer$connect$4.invokeSuspend(SrtProducer.kt:119)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3
![Screenshot from 2023-04-14 18-34-20](https://user-images.githubusercontent.com/84388209/232051602-b987b3ee-e7f2-4816-87dd-c44734aa2d65.png)
![Screenshot from 2023-04-14 18-35-43](https://user-images.githubusercontent.com/84388209/232051784-1298e7e9-d49d-40d9-861b-6bdebdcd2594.png)

**Comment by HitanshuIntern** [comment]
issue solve

**Comment by ThibaultBee** [comment]
Hi,

How do you solve the issue? That might interest other user.
